=== makerforceio/auto_emojiboard/hand_gesture_detector/dataset/common/handposture_recognizer.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.idiap.ch/~marcel/PETS2002"
            xmlns="http://www.idiap.ch/~marcel/PETS2002"
            elementFormDefault="qualified">

<xsd:annotation>
  <xsd:documentation>
    XML Schema (W3C Recommendation 2 May 2001)
    For 2nd IEEE International Workshop on Performance Evaluation of Tracking and Surveillance
    Edited by PETS2001.Reading.JMF (J.M.Ferryman@reading.ac.uk)
   
    Revision: 1.0 of Mon Jun 18 19:43:35 2001 by
      PETS2001.Reading.JMF (J.M.Ferryman@reading.ac.uk)

    Revision: 2.0 of Tue Feb 26 14:00:00 2002 by
      PETS2002.IDIAP.SM (marcel@idiap.ch)

  </xsd:documentation>
</xsd:annotation>

<xsd:element  name="handposture_recognizer">
<xsd:complexType>
  <xsd:sequence>
    <xsd:element ref="header"    minOccurs="1"  maxOccurs="1" />
    <xsd:element ref="sequence"  minOccurs="1"  maxOccurs="1" />
  </xsd:sequence>
</xsd:complexType>
</xsd:element>

<xsd:element  name="header">
<xsd:complexType>
  <xsd:sequence>
    <xsd:element ref="recording"  minOccurs="1"  maxOccurs="1" />
    <xsd:element ref="software"   minOccurs="1"  maxOccurs="1" />
  </xsd:sequence>
</xsd:complexType>
</xsd:element>

<xsd:element  name="recording">
<xsd:complexType>
  <xsd:attribute name="site"     type="xsd:string"   use="required" />
  <xsd:attribute name="date"     type="xsd:string"   use="required" />
</xsd:complexType>
</xsd:element>

<xsd:element  name="software">
<xsd:complexType>
  <xsd:sequence>
    <xsd:element ref="parameters"  minOccurs="1" maxOccurs="1"/>
  </xsd:sequence>

  <xsd:attribute name="name"      type="xsd:string"  use="required" />
  <xsd:attribute name="platform"  type="xsd:string"  use="required" />
  <xsd:attribute name="version"   type="xsd:double"  use="required" />
  <xsd:attribute name="run_date"  type="xsd:string"  use="required" />
</xsd:complexType>
</xsd:element>

  <!--  The following defines parameters which may be used in the tracker - set as appropriate for the tracker used in your application, or leave undefined. -->

<xsd:element  name="parameters">
<xsd:complexType> 
  <xsd:attribute name="param_1"       type="xsd:integer"  use="required" />
  <xsd:attribute name="param_2"	      type="xsd:integer"  use="required" />
  <xsd:attribute name="param_3"       type="xsd:integer"  use="required" />
  <xsd:attribute name="param_4"       type="xsd:integer"  use="required" />
  <xsd:attribute name="param_5"       type="xsd:integer"  use="required" />
  <xsd:attribute name="param_6"       type="xsd:integer"  use="required" />
</xsd:complexType>
</xsd:element>

 <!--  The following states that a sequence consists of at least one frame, the upper limit in the number of frames is infinite. --> 

<xsd:element  name="sequence">
<xsd:complexType>
  <xsd:sequence>
    <xsd:element ref="frame"  minOccurs="1"  maxOccurs="unbounded" />
  </xsd:sequence>
</xsd:complexType>
</xsd:element>

<xsd:element  name="frame">
<xsd:complexType>
  <xsd:sequence>
    <xsd:element ref="object" minOccurs="1"  maxOccurs="1" />
  </xsd:sequence>

  <xsd:attribute name="id"          	type="xsd:string"  use="required" />
  <xsd:attribute name="num_objects"	type="xsd:integer"  use="required" />
  <xsd:attribute name="xdim"    	type="xsd:integer"  use="required" />
  <xsd:attribute name="ydim"    	type="xsd:integer"  use="required" />
  <xsd:attribute name="colour"  	type="xsd:integer"  use="required" />
</xsd:complexType>
</xsd:element>


<xsd:element  name="object">
<xsd:complexType>
  <xsd:sequence>

    <!-- results of tracking for object in 2D coordinates and in 3D.  It is sifficient to report results in 3D by mapping 2D coordinates to 3D under the camera calibration.  You should minimally report 2D results, and leave 3D results undefined -->

    <xsd:element ref="info2d"     minOccurs="1"  maxOccurs="1" />
  </xsd:sequence>

  <!-- object numeric identifier and type.  The type should be defined as 0 for person, 1 for vehicle or >1 for other objects -->

  <xsd:attribute name="id"      type="xsd:integer"  use="required" />
  <xsd:attribute name="type"    type="xsd:string"  use="required" />
</xsd:complexType>
</xsd:element>

<xsd:element  name="info2d">
<xsd:complexType> 

  <!-- object 2D position (centroid defined in pixels (xpos,ypos), and bounding box in pixels) -->

  <xsd:attribute name="xpos"  type="xsd:integer"  use="required" />
  <xsd:attribute name="ypos"  type="xsd:integer"  use="required" />
  <xsd:attribute name="xmin"  type="xsd:integer"  use="required" />
  <xsd:attribute name="xmax"  type="xsd:integer"  use="required" />
  <xsd:attribute name="ymin"  type="xsd:integer"  use="required" />
  <xsd:attribute name="ymax"  type="xsd:integer"  use="required" />
</xsd:complexType>
</xsd:element>

</xsd:schema>

=== makerforceio/auto_emojiboard/hand_gesture_detector/dataset/triesch/triesch_train.xml
<?xml version='1.0' encoding='ISO-8859-1' ?>


<!--
-->
<!--  File of hand postures coordinates/identities from Jochen Triesch Gallery.

      Protocol : Triesch
      DataSet  : Train

-->
 

<handposture_recognizer  xmlns="http://www.idiap.ch/~marcel/PETS2002"
		    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		    xsi:schemaLocation=
                     "http://www.idiap.ch/~marcel/PETS2002
                      http://www.idiap.ch/~marcel/PETS2002/XML/handposture_recognizer.xsd">

  <!-- this is a comment ... add more as appropriate -->

  <header>
        <recording site="PETS2002 (IDIAP)" date="02/26/02"/>
        <software name="GROUND TRUTH" platform="SOLARIS" version="1" run_date="02/26/02">
            <parameters param_1="0" param_2="0" param_3="0" param_4="0" param_5="0" param_6="0"/>
        </software>
  </header>
  <sequence>
 
  <frame id="bfritza1.pgm" num_objects="1">
  	<object id="1" type="a">
  		<info2d xpos="63" ypos="82" xmin="40" xmax="86" ymin="57" ymax="107"/>
  	</object>
  </frame>
  <frame id="bfritza2.pgm" num_objects="1">
  	<object id="1" type="a">
  		<info2d xpos="69" ypos="80" xmin="45" xmax="93" ymin="57" ymax="103"/>
  	</object>
  </frame>
  <frame id="bfritzb1.pgm" num_objects="1">
  	<object id="1" type="b">
  		<info2d xpos="71" ypos="66" xmin="52" xmax="91" ymin="26" ymax="106"/>
  	</object>
  </frame>
  <frame id="bfritzb2.pgm" num_objects="1">
  	<object id="1" type="b">
  		<info2d xpos="75" ypos="67" xmin="55" xmax="95" ymin="29" ymax="106"/>
  	</object>
  </frame>
  <frame id="bfritzc1.pgm" num_objects="1">
  	<object id="1" type="c">
  		<info2d xpos="74" ypos="81" xmin="45" xmax="104" ymin="55" ymax="108"/>
  	</object>
  </frame>
  <frame id="bfritzc2.pgm" num_objects="1">
  	<object id="1" type="c">
  		<info2d xpos="80" ypos="82" xmin="52" xmax="109" ymin="56" ymax="108"/>
  	</object>
  </frame>
  <frame id="bfritzd1.pgm" num_objects="1">
  	<object id="1" type="d">
  		<info2d xpos="64" ypos="70" xmin="46" xmax="83" ymin="29" ymax="112"/>
  	</object>
  </frame>
  <frame id="bfritzd2.pgm" num_objects="1">
  	<object id="1" type="d">
  		<info2d xpos="67" ypos="68" xmin="48" xmax="86" ymin="28" ymax="108"/>
  	</object>
  </frame>
  <frame id="bfritzg1.pgm" num_objects="1">
  	<object id="1" type="g">
  		<info2d xpos="61" ypos="94" xmin="27" xmax="95" ymin="72" ymax="116"/>
  	</object>
  </frame>
  <frame id="bfritzg2.pgm" num_objects="1">
  	<object id="1" type="g">
  		<info2d xpos="58" ypos="81" xmin="28" xmax="89" ymin="61" ymax="101"/>
  	</object>
  </frame>
  <frame id="bfritzh1.pgm" num_objects="1">
  	<object id="1" type="h">
  		<info2d xpos="55" ypos="89" xmin="24" xmax="87" ymin="68" ymax="110"/>
  	</object>
  </frame>
  <frame id="bfritzh2.pgm" num_objects="1">
  	<object id="1" type="h">
  		<info2d xpos="66" ypos="86" xmin="34" xmax="98" ymin="65" ymax="107"/>
  	</object>
  </frame>
  <frame id="bfritzi1.pgm" num_objects="1">
  	<object id="1" type="i">
  		<info2d xpos="61" ypos="76" xmin="41" xmax="81" ymin="44" ymax="108"/>
  	</object>
  </frame>
  <frame id="bfritzi2.pgm" num_objects="1">
  	<object id="1" type="i">
  		<info2d xpos="67" ypos="77" xmin="47" xmax="87" ymin="45" ymax="110"/>
  	</object>
  </frame>
  <frame id="bfritzl1.pgm" num_objects="1">
  	<object id="1" type="l">
  		<info2d xpos="86" ypos="74" xmin="51" xmax="121" ymin="35" ymax="114"/>
  	</object>
  </frame>
  <frame id="bfritzl2.pgm" num_objects="1">
  	<object id="1" type="l">
  		<info2d xpos="87" ypos="74" xmin="53" xmax="121" ymin="36" ymax="112"/>
  	</object>
  </frame>
  <frame id="bfritzv1.pgm" num_objects="1">
  	<object id="1" type="v">
  		<info2d xpos="55" ypos="70" xmin="33" xmax="77" ymin="28" ymax="112"/>
  	</object>
  </frame>
  <frame id="bfritzv2.pgm" num_objects="1">
  	<object id="1" type="v">
  		<info2d xpos="66" ypos="69" xmin="43" xmax="89" ymin="29" ymax="110"/>
  	</object>
  </frame>
  <frame id="bfritzy1.pgm" num_objects="1">
  	<object id="1" type="y">
  		<info2d xpos="60" ypos="82" xmin="28" xmax="92" ymin="56" ymax="109"/>
  	</object>
  </frame>
  <frame id="bfritzy2.pgm" num_objects="1">
  	<object id="1" type="y">
  		<info2d xpos="67" ypos="82" xmin="35" xmax="99" ymin="56" ymax="109"/>
  	</object>
  </frame>
  <frame id="haloosa1.pgm" num_objects="1">
  	<object id="1" type="a">
  		<info2d xpos="56" ypos="68" xmin="32" xmax="80" ymin="42" ymax="95"/>
  	</object>
  </frame>
  <frame id="haloosa2.pgm" num_objects="1">
  	<object id="1" type="a">
  		<info2d xpos="63" ypos="63" xmin="39" xmax="87" ymin="39" ymax="88"/>
  	</object>
  </frame>
  <frame id="haloosb1.pgm" num_objects="1">
  	<object id="1" type="b">
  		<info2d xpos="53" ypos="54" xmin="32" xmax="74" ymin="10" ymax="98"/>
  	</object>
  </frame>
  <frame id="haloosb2.pgm" num_objects="1">
  	<object id="1" type="b">
  		<info2d xpos="52" ypos="53" xmin="31" xmax="73" ymin="10" ymax="97"/>
  	</object>
  </frame>
  <frame id="haloosc1.pgm" num_objects="1">
  	<object id="1" type="c">
  		<info2d xpos="73" ypos="63" xmin="48" xmax="98" ymin="33" ymax="93"/>
  	</object>
  </frame>
  <frame id="haloosc2.pgm" num_objects="1">
  	<object id="1" type="c">
  		<info2d xpos="74" ypos="69" xmin="47" xmax="101" ymin="39" ymax="100"/>
  	</object>
  </frame>
  <frame id="haloosd1.pgm" num_objects="1">
  	<object id="1" type="d">
  		<info2d xpos="57" ypos="55" xmin="32" xmax="83" ymin="15" ymax="95"/>
  	</object>
  </frame>
  <frame id="haloosd2.pgm" num_objects="1">
  	<object id="1" type="d">
  		<info2d xpos="60" ypos="56" xmin="37" xmax="83" ymin="14" ymax="98"/>
  	</object>
  </frame>
  <frame id="haloosg1.pgm" num_objects="1">
  	<object id="1" type="g">
  		<info2d xpos="52" ypos="70" xmin="20" xmax="84" ymin="47" ymax="93"/>
  	</object>
  </frame>
  <frame id="haloosg2.pgm" num_objects="1">
  	<object id="1" type="g">
  		<info2d xpos="58" ypos="69" xmin="24" xmax="92" ymin="45" ymax="93"/>
  	</object>
  </frame>
  <frame id="haloosh1.pgm" num_objects="1">
  	<object id="1" type="h">
  		<info2d xpos="60" ypos="62" xmin="27" xmax="94" ymin="40" ymax="84"/>
  	</object>
  </frame>
  <frame id="haloosh2.pgm" num_objects="1">
  	<object id="1" type="h">
  		<info2d xpos="54" ypos="70" xmin="19" xmax="89" ymin="46" ymax="94"/>
  	</object>
  </frame>
  <frame id="haloosi1.pgm" num_objects="1">
  	<object id="1" type="i">
  		<info2d xpos="55" ypos="60" xmin="35" xmax="76" ymin="29" ymax="92"/>
  	</object>
  </frame>
  <frame id="haloosi2.pgm" num_objects="1">
  	<object id="1" type="i">
  		<info2d xpos="60" ypos="63" xmin="40" xmax="80" ymin="30" ymax="97"/>
  	</object>
  </frame>
  <frame id="haloosl1.pgm" num_objects="1">
  	<object id="1" type="l">
  		<info2d xpos="61" ypos="61" xmin="22" xmax="100" ymin="17" ymax="106"/>
  	</object>
  </frame>
  <frame id="haloosl2.pgm" num_objects="1">
  	<object id="1" type="l">
  		<info2d xpos="62" ypos="61" xmin="25" xmax="99" ymin="18" ymax="105"/>
  	</object>
  </frame>
  <frame id="haloosv1.pgm" num_objects="1">
  	<object id="1" type="v">
  		<info2d xpos="49" ypos="57" xmin="22" xmax="77" ymin="11" ymax="103"/>
  	</object>
  </frame>
  <frame id="haloosv2.pgm" num_objects="1">
  	<object id="1" type="v">
  		<info2d xpos="56" ypos="62" xmin="34" xmax="78" ymin="19" ymax="106"/>
  	</object>
  </frame>
  <frame id="haloosy1.pgm" num_objects="1">
  	<object id="1" type="y">
  		<info2d xpos="61" ypos="68" xmin="25" xmax="97" ymin="35" ymax="101"/>
  	</object>
  </frame>
  <frame id="haloosy2.pgm" num_objects="1">
  	<object id="1" type="y">
  		<info2d xpos="50" ypos="72" xmin="13" xmax="87" ymin="47" ymax="97"/>
  	</object>
  </frame>
  <frame id="mpoetza1.pgm" num_objects="1">
  	<object id="1" type="a">
  		<info2d xpos="64" ypos="78" xmin="46" xmax="82" ymin="59" ymax="97"/>
  	</object>
  </frame>
  <frame id="mpoetza2.pgm" num_objects="1">
  	<object id="1" type="a">
  		<info2d xpos="57" ypos="77" xmin="37" xmax="78" ymin="59" ymax="96"/>
  	</object>
  </frame>
  <frame id="mpoetzb1.pgm" num_objects="1">
  	<object id="1" type="b">
  		<info2d xpos="53" ypos="68" xmin="35" xmax="72" ymin="30" ymax="107"/>
  	</object>
  </frame>
  <frame id="mpoetzb2.pgm" num_objects="1">
  	<object id="1" type="b">
  		<info2d xpos="60" ypos="67" xmin="43" xmax="77" ymin="29" ymax="105"/>
  	</object>
  </frame>
  <frame id="mpoetzc1.pgm" num_objects="1">
  	<object id="1" type="c">
  		<info2d xpos="55" ypos="82" xmin="29" xmax="81" ymin="56" ymax="108"/>
  	</object>
  </frame>
  <frame id="mpoetzc2.pgm" num_objects="1">
  	<object id="1" type="c">
  		<info2d xpos="64" ypos="74" xmin="38" xmax="91" ymin="44" ymax="105"/>
  	</object>
  </frame>
  <frame id="mpoetzd1.pgm" num_objects="1">
  	<object id="1" type="d">
  		<info2d xpos="64" ypos="70" xmin="46" xmax="83" ymin="36" ymax="105"/>
  	</object>
  </frame>
  <frame id="mpoetzd2.pgm" num_objects="1">
  	<object id="1" type="d">
  		<info2d xpos="60" ypos="66" xmin="42" xmax="79" ymin="35" ymax="97"/>
  	</object>
  </frame>
  <frame id="mpoetzg1.pgm" num_objects="1">
  	<object id="1" type="g">
  		<info2d xpos="55" ypos="86" xmin="29" xmax="81" ymin="65" ymax="107"/>
  	</object>
  </frame>
  <frame id="mpoetzg2.pgm" num_objects="1">
  	<object id="1" type="g">
  		<info2d xpos="45" ypos="80" xmin="20" xmax="71" ymin="60" ymax="100"/>
  	</object>
  </frame>
  <frame id="mpoetzh1.pgm" num_objects="1">
  	<object id="1" type="h">
  		<info2d xpos="56" ypos="79" xmin="28" xmax="84" ymin="58" ymax="101"/>
  	</object>
  </frame>
  <frame id="mpoetzh2.pgm" num_objects="1">
  	<object id="1" type="h">
  		<info2d xpos="39" ypos="84" xmin="12" xmax="66" ymin="64" ymax="104"/>
  	</object>
  </frame>
  <frame id="mpoetzi1.pgm" num_objects="1">
  	<object id="1" type="i">
  		<info2d xpos="59" ypos="74" xmin="41" xmax="78" ymin="44" ymax="104"/>
  	</object>
  </frame>
  <frame id="mpoetzi2.pgm" num_objects="1">
  	<object id="1" type="i">
